language: python
cache:
  - pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# setup environment
before_install:
  - virtualenv venv
  - source .env
# command to install dependencies
install: "pip install requests"
# run tests
script: python tests/run_tests.py
